"
"" 
# Microdown

This notebook is a learning step to understand **Microdown**, 
the markup language used in Pharo.

We start with a look at the _special symbols_ that trigger different formattings:
""

MicMicrodownSharedPool class>>#initialize
"
Class {
	#name : 'BookletDSstMicrodownNotebook',
	#superclass : 'CTClassCommentAutoNotebook',
	#category : 'Booklet-DSst-Tests',
	#package : 'Booklet-DSst-Tests'
}
