"
""# Intro

The publication subject of this page has the following reference
  

which is the starting point to enhance our own Smalltalk class""

RSVanDerPloegTreeLayout ignoreOutputBecause: RSVanDerPloegTreeLayout class comment.

"" [`RSVanDerPloegTreeLayout`](https://github.com/massimo-nocentini/Roassal3/blob/master/src/Roassal3-Layouts/RSVanDerPloegTreeLayout.class.st) to be faster by coding the core algorithm direclty in C and using Lua as intermediate for both describing the tree nodes and interfacing with C.

We represent the tree used in the paper as case study to spot the core points of the algorithms looks like either"".

NonLayeredTidyTreesTest>>#testTreeLayout3_small.

"
Class {
	#name : 'BookletDSstVanDerPloegNotebook',
	#superclass : 'CTClassCommentAutoNotebook',
	#category : 'Booklet-DSst-Tests',
	#package : 'Booklet-DSst-Tests'
}
