"
"" 

# SICP.st

This sequence of sheets is a benchmark to render large amount of text directly from (Pharo) Smalltalk.

We should be aware of a [pdf release](https://web.mit.edu/6.001/6.037/sicp.pdf) of the original book, published in full on the [MIT's companion web page](https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/6515/sicp.zip/full-text/book/book.html).

""
"
Class {
	#name : #BookletSICPNotebook,
	#superclass : #CTClassCommentAutoNotebook,
	#category : #'Booklet-DSst-Tests'
}
